### ISSUE TITLE
Request: SD card image for all boards

### ISSUE THREAD

**Issue by StMaHa** [radxa/rabian-build#2]
Some user prefer to use a SD card Image instead of NAND
- in case OTG is broken
- in case of simple backup
- in case of simple editing of the SD card in a Desktop PC
  therefor it would invaluable

**Comment by hipboi** [comment]
rock and rock pro will be added shortly, rock2 needs some more time.

**Comment by hipboi** [comment]
Now all boards supports sdcard build.

**Comment by henrivdr** [comment]
Hi hipboi. Do you have the link for Rabian SD card image for Rock (2013) board please?  I cannot find it on 
http://wiki.radxa.com/Rock/prebuilt_images

**Comment by henrivdr** [comment]
Hi hipboi. Do you have the link for Rabian SD card image for Rock (2013) board please?  I cannot find it on 
http://wiki.radxa.com/Rock/prebuilt_images
