### ISSUE TITLE
MPlayer and VLC problems when playing mpeg4 movies

### ISSUE THREAD

**Issue by ghost** [radxa/rabian-build#3]
Hello,

I own a radxa_full 2013 and I have been trying to play an mpeg4 file on Rabian and I have 2 issues:

MPlayer plays fine, but when I set to full screen, it does not stretch the movie to full screen, it only plays the default movie resolution (which is 320x240) in the center of the screen.

VLC has stuttering issues, I mean i see a few laggy frames at start and then it freezes completely. 

Audio from the movie works fine in both cases.

 I have not tryed xmbc (or kodi).

If you need any more info from me, please don't hesitate to ask. I will try to respond as fast as possible.

**Comment by jack-ma** [comment]
Hello, you can add mplayer "zoom" config.

sudo vim.tiny ~/.mplayer/config
#Write your default config options here!
zoom="yes"

**Comment by ghost** [comment]
@jack-ma Hello. Adding zoom="yes" to default config options solved my problem with mplayer. I can watch mpeg4 movies in fullscreen now. 

Please tell me if there is anything I must do to mark this bug as resolved.

**Comment by hipboi** [comment]
@iandrei01 ok, close it.
